import type { GameObjects, Scene } from "phaser";
import { RENDER_DEPTHS, THEME_COLORS, THEME_TYPOGRAPHY, colorToCss } from "../rendering";
import { getAccessibilitySettings } from "../game/accessibility";
import { calculateTooltipPosition } from "./presentationLayout";

const managers = new WeakMap<Scene, TooltipManager>();

export class TooltipManager {
  private readonly background: GameObjects.Rectangle;
  private readonly text: GameObjects.Text;
  public constructor(private readonly scene: Scene) {
    this.background = scene.add.rectangle(0, 0, 1, 1, THEME_COLORS.panelRaised, 0.98).setOrigin(0).setStrokeStyle(1, THEME_COLORS.panelBorder).setDepth(RENDER_DEPTHS.ui + 300).setScrollFactor(0).setVisible(false);
    this.text = scene.add.text(0, 0, "", { color: colorToCss(THEME_COLORS.primaryText), fontFamily: THEME_TYPOGRAPHY.fontFamily, fontSize: THEME_TYPOGRAPHY.statusSize, wordWrap: { width: 240 } }).setDepth(RENDER_DEPTHS.ui + 301).setScrollFactor(0).setVisible(false);
    scene.cameras.main.ignore([this.background, this.text]);
    scene.events.once("shutdown", () => {
      managers.delete(scene);
    });
  }
  public register(target: GameObjects.GameObject, getContent: () => string): void {
    target.on("pointerover", () => this.show(getContent()));
    target.on("pointermove", () => this.position());
    target.on("pointerout", () => this.hide());
  }
  public show(content: string): void { this.text.setText(content).setVisible(true); this.background.setVisible(true); this.position(); }
  public hide(): void { this.text.setVisible(false); this.background.setVisible(false); }
  private position(): void {
    const pointer = this.scene.input.activePointer;
    const uiScale = getAccessibilitySettings(this.scene.registry).uiScale;
    const pointerX = pointer.x / uiScale;
    const pointerY = pointer.y / uiScale;
    const viewportWidth = this.scene.scale.width / uiScale;
    const viewportHeight = this.scene.scale.height / uiScale;
    const width = Math.min(250, Math.max(130, this.text.width + 16));
    const height = this.text.height + 14;
    const { x, y } = calculateTooltipPosition(pointerX, pointerY, width, height, viewportWidth, viewportHeight);
    this.background.setPosition(x, y).setSize(width, height);
    this.text.setPosition(x + 8, y + 7);
  }
}

export function getTooltipManager(scene: Scene): TooltipManager {
  let manager = managers.get(scene);
  if (manager === undefined) { manager = new TooltipManager(scene); managers.set(scene, manager); }
  return manager;
}

export const TOOLTIP_CATALOG = Object.freeze({
  Materials: "Construction and expedition resource. Produced by staffed, powered Forests.",
  Food: "Feeds the population, funds recruitment, and supports growth.",
  Power: "Generated by staffed Power Plants and consumed by staffed production buildings.",
  Workers: "Assigned to production buildings and expeditions.",
  Population: "Colonists supported by housing and Food.",
  RP: "Research Points produced by staffed, powered Labs.",
});
